"""empty message

Revision ID: 4cb84d91811e
Revises: 738d30e57045
Create Date: 2021-12-15 00:57:11.695681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cb84d91811e'
down_revision = '738d30e57045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('thumbnail_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'thumbnail_url')
    # ### end Alembic commands ###
