"""empty message

Revision ID: 8c93c786266d
Revises: 4cb84d91811e
Create Date: 2021-12-21 14:28:32.839364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c93c786266d'
down_revision = '4cb84d91811e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('img', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'img')
    op.drop_column('user', 'bio')
    # ### end Alembic commands ###
